apiVersion: v1
kind: Service
metadata:
  name: {{ include "ecom-api.api.fullname" . }}
  labels:
    {{- include "ecom-api.labels" . | nindent 4 }}
    {{- include "ecom-api.selectorLabels" (dict "ctx" . "component" "api") | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  selector:
    {{- include "ecom-api.selectorLabels" (dict "ctx" . "component" "api") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      {{- if and (eq .Values.api.service.type "NodePort") .Values.api.service.nodePort }}
      nodePort: {{ .Values.api.service.nodePort }}
      {{- end }}
